-- MySQL Script generated by MySQL Workbench
-- Wed Jan  8 08:52:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Prospecte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`devis` ;




-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Technicien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Technicien` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Technicien` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `coutHoraire` decimal(8,2),
  `grade` varchar(45),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`commercial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`commercial` ;

CREATE TABLE IF NOT EXISTS `mydb`.`commercial` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `pourcentage` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prospecte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prospecte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prospecte` (
  `IDcommercial` INT NOT NULL,
  `IDClient` INT NOT NULL,
  `dateRV` DATE NULL,
  `modif` VARCHAR(45) NULL,
  PRIMARY KEY (`IDcommercial`, `IDClient`),
  CONSTRAINT `fk_commercial_has_Client_commercial`
    FOREIGN KEY (`IDcommercial`)
    REFERENCES `mydb`.`commercial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commercial_has_Client_Client1`
    FOREIGN KEY (`IDClient`)
    REFERENCES `mydb`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`devis`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`devis` (
    `num` INT NOT NULL PRIMARY KEY,
    `nom` VARCHAR(45) NOT NULL,
    `montant` DECIMAL(8 , 2 ) NOT NULL,
    `dateProp` DATE NOT NULL,
    `dateSignature` DATE NOT NULL,
    `modif` VARCHAR(45) NOT NULL,
    `clientID` int not null,
    `projetID` int not null,
      CONSTRAINT `fk_devisClient`
    FOREIGN KEY (`clientID`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devisProjet`
    FOREIGN KEY (`projetID`)
    REFERENCES `mydb`.`projet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `mydb`.`Facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Facture` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Facture` (
  `num` INT NOT NULL,
  `numDevis` int,
  PRIMARY KEY (`num`),
    CONSTRAINT `fk_factureDevis`
    FOREIGN KEY (`numDevis`)
    REFERENCES `mydb`.`devis` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`Matériel_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Matériel_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Matériel_type` (
  `ID` INT NOT NULL,
  `nom` varchar(45),
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matériel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Matériel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Matériel` (
  `ID` INT NOT NULL,
  `nom` varchar(45),
  `IDType` int,
  PRIMARY KEY (`ID`),
    CONSTRAINT `fk_matérielMatériel_type`
    FOREIGN KEY (`IDtype`)
    REFERENCES `mydb`.`matériel_type` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Projet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Projet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Projet` (
  `ID` INT NOT NULL,
  `commercialID` int,
  `nom` varchar(45) NOT NULL,
  `duréeEstimée` int,
  `duréeFinale` int,
  `statut` varchar(45),
  PRIMARY KEY (`ID`),
    CONSTRAINT `fk_projetCommercial`
    FOREIGN KEY (`commercialID`)
    REFERENCES `mydb`.`Commercial` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nécessite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nécessite` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Nécessite` (
  `projetID` INT NOT NULL,
  `matérielID` INT NOT NULL,
  `quantité` int,
  `dateCommande` date,
  `dateLivraison` date,
  `prixAchat` decimal(8,2),
  PRIMARY KEY (`projetID`, `matérielID`),
    CONSTRAINT `fk_nécessiteProjet`
    FOREIGN KEY (`projetID`)
    REFERENCES `mydb`.`Projet` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_nécessiteMatériel`
    FOREIGN KEY (`matérielID`)
    REFERENCES `mydb`.`Matériel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compétence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Compétence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Compétence` (
  `ID` INT NOT NULL,
  `nom` varchar(45),
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Activité_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Activité_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Activité_type` (
  `ID` INT NOT NULL,
  `nom` varchar(45) unique,
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Activité`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Activité` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Activité` (
  `ID` INT NOT NULL,
  `duréePrévue` INT,
  `résumé` varchar(45),
   `détail` varchar(45),
  `statut` varchar(45) ,
  `IDType` int,
  `dateDébut` date default null,
  `dateFin` date default null,
  PRIMARY KEY (`ID`),
    CONSTRAINT `fk_activitéActivité_type`
    FOREIGN KEY (`IDType`)
    REFERENCES `mydb`.`activité_type` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compose`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Compose` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Compose` (
  `projetID` INT NOT NULL,
  `activitéID` INT NOT NULL,
  PRIMARY KEY (`projetID`,`ActivitéID`),
    CONSTRAINT `fk_composeActivité`
    FOREIGN KEY (`activitéID`)
    REFERENCES `mydb`.`activité` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_composeProjet`
    FOREIGN KEY (`projetID`)
    REFERENCES `mydb`.`Projet` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Mobilise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mobilise` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mobilise` (
  `compétenceID` INT NOT NULL,
  `activité_typeID` INT NOT NULL,
  PRIMARY KEY (`compétenceID`,`Activité_typeID`),
    CONSTRAINT `fk_mobiliseActivité_type`
    FOREIGN KEY (`activité_typeID`)
    REFERENCES `mydb`.`activité_type` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_mobiliseCompétence`
    FOREIGN KEY (`compétenceID`)
    REFERENCES `mydb`.`Compétence` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Affecté`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Affecté` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Affecté` (
  `technicienID` INT NOT NULL,
  `activitéID` INT NOT NULL,
  PRIMARY KEY (`technicienID`,`ActivitéID`),
    CONSTRAINT `fk_affectéActivité`
    FOREIGN KEY (`activitéID`)
    REFERENCES `mydb`.`activité` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_affectéTechnicien`
    FOREIGN KEY (`technicienID`)
    REFERENCES `mydb`.`technicien` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Possède`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Possède` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Possède` (
    `compétenceID` INT NOT NULL,
    `technicienID` INT NOT NULL,
    `niveau` VARCHAR(45),
    PRIMARY KEY (`technicienID` , `compétenceID`),
    CONSTRAINT `fk_possèdeCompétence` FOREIGN KEY (`compétenceID`)
        REFERENCES `mydb`.`compétence` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_possèdeTechnicien` FOREIGN KEY (`technicienID`)
        REFERENCES `mydb`.`technicien` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = InnoDB;

CREATE INDEX `fk_commercial_has_Client_Client1_idx` ON `mydb`.`prospecte` (`IDClient` ASC);

CREATE INDEX `fk_commercial_has_Client_commercial_idx` ON `mydb`.`prospecte` (`IDcommercial` ASC);


-- --------------------------------------------------
-- Ajout AG pour les utilisateurs
-- --------------------------------------------------
DROP TABLE IF EXISTS  `mydb`.`Utilisateur`;

CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  ID INT NOT NULL,
  LOGIN VARCHAR(45) UNIQUE NOT NULL,
  PASSWORD VARCHAR(128),
  TYPE_UTILISATEUR VARCHAR(64),
  PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE INDEX idx_login ON `mydb`.`Utilisateur` (LOGIN ASC);

ALTER TABLE `mydb`.`Client` 
ADD UTILISATEUR_ID INT,
add FOREIGN KEY(UTILISATEUR_ID) REFERENCES `mydb`.`Utilisateur`(ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `mydb`.`Technicien`
ADD UTILISATEUR_ID INT,
add FOREIGN KEY(UTILISATEUR_ID) REFERENCES `mydb`.`Utilisateur`(ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `mydb`.`commercial`
ADD UTILISATEUR_ID INT,
add FOREIGN KEY(UTILISATEUR_ID) REFERENCES `mydb`.`Utilisateur`(ID) ON DELETE RESTRICT ON UPDATE RESTRICT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
